version: '3.3'
services:
  es7.4:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es7.4
    hostname: es7.4
    environment:
      - node.name=es7.4
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
