version: '3.3'
services:
  es7.4:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es7.5
    hostname: es7.5
    environment:
      - node.name=es7.5
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
