version: '3.3'
services:
  es6.8:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
    container_name: es6.8
    hostname: es6.8
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

